/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Arreglos;
import Modelo.CitaMedica;
import Modelo.Especialidad;
import Modelo.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class JFrame_Principal extends javax.swing.JFrame {

    Arreglos objArreglos = new Arreglos();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Principal.class.getName());

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
        objArreglos.ordenarEspecialidades(tbl_demuestra);
    }
    
    public void actualizarComboEspecialidad(){
        cbo_especialidad.removeAllItems();
        
        for (int i = 0; i < objArreglos.getCantidadEspecialidades(); i++){
            cbo_especialidad.addItem(objArreglos.getEspecialidad(i).toString());
        }
    }
    
    public void actualizarComboMedico(){
        cbo_medico.removeAllItems();
        
        for (int i = 0; i < objArreglos.getCantidadMedicos(); i++){
            cbo_medico.addItem(objArreglos.getMedico(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tbd_registros = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spn_codigo = new javax.swing.JSpinner();
        txt_area_especializada = new javax.swing.JTextField();
        txt_costoconsulta = new javax.swing.JTextField();
        btn_registrar_especialidad = new javax.swing.JButton();
        spn_piso = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dni_medico = new javax.swing.JTextField();
        txt_nombre_medico = new javax.swing.JTextField();
        spn_aniosesperiencia = new javax.swing.JSpinner();
        spn_jornada = new javax.swing.JSpinner();
        cbo_especialidad = new javax.swing.JComboBox<>();
        btn_registrar_medico = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbo_medico = new javax.swing.JComboBox<>();
        spn_fecha = new javax.swing.JSpinner();
        btn_registrar_citas = new javax.swing.JButton();
        txt_especialidad_cita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_demuestra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("GESTION DE CLÍNICA MÉDICA Y CITAS ESPECIALIZADAS");

        tbd_registros.setForeground(new java.awt.Color(51, 51, 255));
        tbd_registros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbd_registrosStateChanged(evt);
            }
        });
        tbd_registros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbd_registrosFocusGained(evt);
            }
        });

        jLabel2.setText("Codigo:");

        jLabel3.setText("Área especializada:");

        jLabel4.setText("Costo de consulta:");

        jLabel6.setText("Piso de ubicacion:");

        spn_codigo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btn_registrar_especialidad.setText("Registrar");
        btn_registrar_especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_especialidadActionPerformed(evt);
            }
        });

        spn_piso.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_area_especializada, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(spn_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(txt_costoconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(spn_piso))
                .addGap(63, 63, 63)
                .addComponent(btn_registrar_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spn_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar_especialidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_area_especializada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_costoconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spn_piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tbd_registros.addTab("REGISTRAR ESPECIALIDAD", jPanel2);

        jLabel7.setText("DNI:");

        jLabel8.setText("Apellidos y nombres:");

        jLabel9.setText("Años de experiencia:");

        jLabel10.setText("Horas semanales:");

        jLabel11.setText("Especialidad:");

        spn_aniosesperiencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spn_jornada.setModel(new javax.swing.SpinnerNumberModel(7, 2, null, 1));

        btn_registrar_medico.setText("Registrar");
        btn_registrar_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_medicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nombre_medico)
                    .addComponent(spn_aniosesperiencia)
                    .addComponent(spn_jornada)
                    .addComponent(cbo_especialidad, 0, 314, Short.MAX_VALUE)
                    .addComponent(txt_dni_medico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_registrar_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_dni_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar_medico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nombre_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spn_aniosesperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spn_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbo_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbd_registros.addTab("REGISTRAR MÉDICO", jPanel3);

        jLabel12.setText("Medico:");

        jLabel13.setText("Especialidad:");

        jLabel14.setText("fecha de la cita:");

        cbo_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_medicoActionPerformed(evt);
            }
        });

        spn_fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1776960428447L), null, java.util.Calendar.HOUR_OF_DAY));

        btn_registrar_citas.setText("Registrar");
        btn_registrar_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_citasActionPerformed(evt);
            }
        });

        txt_especialidad_cita.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbo_medico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spn_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(txt_especialidad_cita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btn_registrar_citas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbo_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar_citas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_especialidad_cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tbd_registros.addTab("REGISTRAR CITA", jPanel4);

        tbl_demuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_demuestra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(tbd_registros))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbd_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrar_especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_especialidadActionPerformed
        // TODO add your handling code here:
        String codigo = spn_codigo.getValue().toString();
        String area = txt_area_especializada.getText();
        
        int pisoubicacion = (int) spn_piso.getValue();

        if (area == null || "".equals(area)
                || txt_costoconsulta.getText() == null
                || "".equals(txt_costoconsulta.getText())) {
            JOptionPane.showMessageDialog(null,
                    "Escriba los datos completos",
                    "Error", JOptionPane.WARNING_MESSAGE);
            txt_area_especializada.setText("");
            txt_costoconsulta.setText("");
            spn_codigo.setValue(1);
            spn_piso.setValue(0);
            return;
        }
        
        double costoconsulta;
        
        try {
            costoconsulta = Double.parseDouble(txt_costoconsulta.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un número válio");
            return;
        }
        
        Especialidad objEspecialidad = new Especialidad(codigo, area, costoconsulta, pisoubicacion);

        objArreglos.registrarEspecialidad(objEspecialidad);
        objArreglos.ordenarEspecialidades(tbl_demuestra);
        actualizarComboEspecialidad();

        txt_area_especializada.setText("");
        txt_costoconsulta.setText("");
        spn_codigo.setValue(1);
        spn_piso.setValue(0);

        spn_codigo.requestFocus();


    }//GEN-LAST:event_btn_registrar_especialidadActionPerformed

    private void btn_registrar_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_medicoActionPerformed
        // TODO add your handling code here:
        try {
            String dnimedico = txt_dni_medico.getText();
            String nombre = txt_nombre_medico.getText();
            int aniosexp = (int) spn_aniosesperiencia.getValue();
            int horassemanales = (int) spn_jornada.getValue();
            int pos = cbo_especialidad.getSelectedIndex();
            
            if (pos == -1){
                JOptionPane.showMessageDialog(null, "Seleccione una especialidad");
                return;
            }

            if (dnimedico == null || dnimedico.isEmpty()
                    || nombre == null || nombre.isEmpty()
                    ) {

                JOptionPane.showMessageDialog(null,
                        "Escriba los datos completos",
                        "Error", JOptionPane.WARNING_MESSAGE);
                txt_dni_medico.setText("");
                txt_nombre_medico.setText("");
                spn_aniosesperiencia.setValue(0);
                spn_jornada.setValue(7);
                cbo_especialidad.setSelectedIndex(-1);
                txt_dni_medico.requestFocus();
                return;
            }
          
            Especialidad objEspecialidad = objArreglos.getEspecialidad(pos);

            Medico objMedico = new Medico(dnimedico, nombre, aniosexp, horassemanales, objEspecialidad);

            objArreglos.registrarMedico(objMedico);
            objArreglos.ordenarMedicosPorExp();
            actualizarComboMedico();
            objArreglos.ordenarMedicos(tbl_demuestra);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null,
                    "Escriba los datos completos",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }

        txt_dni_medico.setText("");
        txt_nombre_medico.setText("");
        spn_aniosesperiencia.setValue(0);
        spn_jornada.setValue(7);
        cbo_especialidad.setSelectedIndex(-1);

        txt_dni_medico.requestFocus();


    }//GEN-LAST:event_btn_registrar_medicoActionPerformed

    private void tbd_registrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbd_registrosFocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_tbd_registrosFocusGained

    private void tbd_registrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbd_registrosStateChanged
        // TODO add your handling code here:
        int pos = tbd_registros.getSelectedIndex();
        if (pos == 0) {
            objArreglos.ordenarEspecialidades(tbl_demuestra);
            txt_area_especializada.setText("");
            txt_costoconsulta.setText("");
            spn_codigo.setValue(1);
            spn_piso.setValue(0);

            spn_codigo.requestFocus();

        } else if (pos == 1) {
            objArreglos.ordenarMedicos(tbl_demuestra);
            txt_dni_medico.setText("");
            txt_nombre_medico.setText("");
            spn_aniosesperiencia.setValue(0);
            spn_jornada.setValue(7);

            txt_dni_medico.requestFocus();
        } else {
            objArreglos.ordenarCitas(tbl_demuestra);
        }
    }//GEN-LAST:event_tbd_registrosStateChanged

    private void btn_registrar_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_citasActionPerformed

        int pos = cbo_medico.getSelectedIndex();
        if (pos == -1) {
            JOptionPane.showMessageDialog(null,
                    "Escriba los datos completos",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Medico objmedico = objArreglos.getMedico(pos);
        Especialidad especialidad = objmedico.getEspecialidad();
        String fecha = spn_fecha.getValue().toString();

        CitaMedica objCitaMedica = new CitaMedica(objmedico, especialidad, fecha);

        objArreglos.registrarCita(objCitaMedica, objmedico.getDniMedico(), objmedico.getEspecialidad().getCodEspecialidad());
        objArreglos.ordenarCitasPorMonto();
        objArreglos.ordenarCitas(tbl_demuestra);

        cbo_medico.setSelectedIndex(-1);
        cbo_medico.requestFocus();

    }//GEN-LAST:event_btn_registrar_citasActionPerformed

    private void cbo_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_medicoActionPerformed
        // TODO add your handling code here:
        int pos = cbo_medico.getSelectedIndex();
        
        if (pos == -1) return;
        
        Medico medico = objArreglos.getMedico(pos);
        txt_especialidad_cita.setText(medico.getEspecialidad().getNombreArea());
    }//GEN-LAST:event_cbo_medicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar_citas;
    private javax.swing.JButton btn_registrar_especialidad;
    private javax.swing.JButton btn_registrar_medico;
    private javax.swing.JComboBox<String> cbo_especialidad;
    private javax.swing.JComboBox<String> cbo_medico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spn_aniosesperiencia;
    private javax.swing.JSpinner spn_codigo;
    private javax.swing.JSpinner spn_fecha;
    private javax.swing.JSpinner spn_jornada;
    private javax.swing.JSpinner spn_piso;
    private javax.swing.JTabbedPane tbd_registros;
    private javax.swing.JTable tbl_demuestra;
    private javax.swing.JTextField txt_area_especializada;
    private javax.swing.JTextField txt_costoconsulta;
    private javax.swing.JTextField txt_dni_medico;
    private javax.swing.JTextField txt_especialidad_cita;
    private javax.swing.JTextField txt_nombre_medico;
    // End of variables declaration//GEN-END:variables
}
